### ISSUE TITLE
Рассылка

### ISSUE THREAD

**Issue by pauldruziak** [startapki/whisky_club#98]
Добрый день!

Рады сообщить, что позиции с последней дегустации уже доступны для [оценивания](http://whisky.vn.ua). 

#### Также хотим сообщить об реализованных улучшениях:

Тепер на странице [архива](http://whisky.vn.ua/meetings) есть возможность фильтровать позиции по: стране, алкоголю и выдержке.

С уважением,
http://whisky.vn.ua

**Comment by pauldruziak** [comment]
@yevhene норм?

**Comment by yevhene** [comment]
@paveldruzyak норм
